### PR TITLE
add volume update eventing

### PR DESCRIPTION
**Pull request by esskar**
This pull request will add a new event `volume` that gets triggered when any of the volumes change.

### CODE REVIEW

**Comment by mikecluck** [comment]
Thanks for the PR! It looks pretty good but there's some tweaks I would recommend. First off, I don't think we need to create the `AndroidVolume` class. There's only one instance of it so we may as well just store everything in the module scope. Something more like this:

```javascript
function onVolumeUpdate(info) {
  cordova.fireWindowEvent('volume', info);
}

function onVolumeError(e) {
  console.log('Error initializing AndroidVolume event: ' + e);
}

const volumeEventHandler = cordova.addWindowEventHandler('volume');
volumeEventHandler.onHasSubscribersChange = function() {
  if (this.numHandlers === 1) {
    exec(onVolumeUpdate, onVolumeError, 'AndroidVolume', 'registerVolumeObserver', []);
  } else if (this.numHandlers === 0) {
    exec(null, null, 'AndroidVolume', 'unregisterVolumeObserver', []);
  }
}

exports.getAlarm        = createGetVolume('getAlarm');
exports.getDTMF         = createGetVolume('getDTMF');
exports.getMusic        = createGetVolume('getMusic');
exports.getNotification = createGetVolume('getNotification');
exports.getRinger       = createGetVolume('getRinger');
exports.getSystem       = createGetVolume('getSystem');
exports.getVoiceCall    = createGetVolume('getVoiceCall');

exports.set             = createSetVolume('setAll');
exports.setAlarm        = createSetVolume('setAlarm');
exports.setAll          = exports.set;
exports.setDTMF         = createSetVolume('setDTMF');
exports.setMusic        = createSetVolume('setMusic');
exports.setNotification = createSetVolume('setNotification');
exports.setRinger       = createSetVolume('setRinger');
exports.setSystem       = createSetVolume('setSystem');
exports.setVoiceCall    = createSetVolume('setVoiceCall');
exports.events          = volumeEventHandler;
```

You'll also notice that I removed all of the `numHandlers` logic. There's only one event channel so we don't need all of that extra logic for adding up other event channels. If another event channel is ever added, then we could add in that logic.

Another thing is that this file uses tabs but it looks like your change use spaces. I'd just like to keep it consistent. What do you think?

**Comment by esskar** [comment]
Looks good to me; some questions:

do we need to export `volumeEventHandler` as events? 
is `this.numHandlers` always save? 

i will push the changes tonight when home

**Comment by mikecluck** [comment]
> do we need to export volumeEventHandler as events?

You're right, it doesn't look like we need to export `volumeEventHandler` since it will fire a `window` level event

> is this.numHandlers always save?

I think so. I don't have my computer setup to test this right now so I was just basing that off of what you wrote haha

**Comment by esskar** [comment]
@MCluck90 improvments pushed

**Comment by mikecluck** [comment]
Looks good to me. Thanks for doing this!

**Pull request merged**
